# Generated by Django 4.1.2 on 2022-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password1",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="password2",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
