# Generated by Django 4.1.2 on 2022-10-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_password1_customuser_password2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
