# Generated by Django 4.1.2 on 2022-10-23 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_album_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 24, 55, 33817, tzinfo=datetime.timezone.utc), editable=False, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
