# Generated by Django 4.1.2 on 2022-10-23 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_album_creation_date_alter_album_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 23, 8, 32, 0, 407060, tzinfo=datetime.timezone.utc), editable=False, verbose_name='creation date'),
        ),
    ]
