# Generated by Django 4.1.2 on 2022-10-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0011_alter_album_cost_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
