# Generated by Django 4.1.2 on 2022-10-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0013_alter_song_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_file",
            field=models.FileField(default="", upload_to="music"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(upload_to="song-images"),
        ),
        migrations.AlterField(
            model_name="song",
            name="name",
            field=models.SlugField(blank=True, default=None),
        ),
    ]
