# Generated by Django 4.1.2 on 2022-10-28 18:09

import albums.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0014_song_audio_file_alter_song_image_alter_song_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(
                upload_to="music",
                validators=[albums.validators.validators.validate_audio],
            ),
        ),
    ]
