# Generated by Django 4.1.2 on 2022-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0016_alter_album_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="release date"
            ),
        ),
    ]
