# Generated by Django 4.1.2 on 2022-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0017_alter_album_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cost",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
