# Generated by Django 4.1.2 on 2022-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['stage_name']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='social_link',
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
